const tableField = {
    '货币资金' : 'huobizijin',
    '交易性金融资产' : 'jiaoyixingjinrongzichan',
    '衍生金融资产' : 'yanshengjinrongzichan',
    '应收票据' : 'yingshoupiju',
    '应收账款' : 'yingshouzhangkuan',
    '预付款项' : 'yufukuanxiang',
    '其他应收款' : 'qitayingshoukuan',
    '存货' : 'cunhuo',
    '一年内到期的非流动资产' : 'yinianneidaodaqidefeiliudongzichan',
    '其他流动资产' : 'qitaliudongzichan',
    '流动资产合计' : 'liudongzichanheji',

    '长期股权投资' : 'changqiguoquanzichan',
    '其他权益工具投资' : 'qitaquanyigongjuzichan',
    '其他非流动金融资产' : 'qitafeiliudongjinrongzichan',
    '投资性房地产' : 'touzixingfangdichan',
    '固定资产' : 'gudingzichan',
    '在建工程' : 'zaijiangongcheng',
    '生产性生物资产' : 'shengchanxingshengwuzichan',
    '使用权资产' : 'shiyongquanzichan',
    '无形资产' : 'wuxingzichan',
    '商誉' : 'shangyu',
    '长期待摊费用' : 'changqidaizhangfeiyong',
    '递延所得税资产' : 'diyansuodeshuizichan',
    '其他非流动资产' : 'qitafeiliudongzichan',
    '非流动资产合计' : 'feiliudongzichanheji',

    '资产总计' : 'zichanzongji',

    '短期借款' : 'duanqijiekuan',
    '交易性金融负债' : 'jiaoyixingjinrongfuzhai',
    '衍生金融负债' : 'yanshengjinrongfuzhai',
    '应付票据' : 'yingfupiju',
    '应付账款' : 'yingfuzhangkuan',
    '合同负债' : 'hetongfuzhai',
    '应付职工薪酬' : 'yingfuzhigongxincha',
    '应交税费' : 'yingjiaoshuifei',
    '其他应付款' : 'qitayingfukuan',
    '应付股利' : 'yingfuguli',
    '其中应付股利' : 'yingfuguli',
    '一年内到期的非流动负债' : 'yinanneidaodaqidefeiliudongfuzhai',
    '其他流动负债' : 'qitaliudongfuzhai',
    '流动负债合计' : 'liudongfuzhaiheji',

    '负债合计' : 'fuzhaiheji',



    '长期借款' : 'changqijiekuan',
    '应付债券' : 'yingfuzhaiquan',
    '租赁负债' : 'zulinfuzhai',
    '长期应付款' : 'changqiyingfukuan',
    '长期应付职工薪酬' : 'changqiyingfuzhigongxincha',
    '递延收益' : 'diyanshouyi',
    '递延所得税负债' : 'diyansuodeshuifuzhai',
    '其他非流动负债' : 'qitafeiliudongfuzhai',
    '非流动负债合计' : 'feiliudongfuzhaiheji',

    '实收资本(或股本)' : 'shishouzibenhuoguben',
    '实收资本' : 'shishouzibenhuoguben',
    '实收资本或股本' : 'shishouzibenhuoguben',
    '资本公积' : 'zibenongji',
    '减库存股' : 'jiankucungu',
    '其他综合收益' : 'qitazongheshouyi',
    '盈余公积' : 'yingyugongji',
    '未分配利润' : 'weifenpeilirun',

    '归属于母公司所有者权益合计' : 'guishumugongsisuoyouzhequanyi',
    '少数股东权益' : 'shaoshugudongquanyi',
    '股东权益合计' : 'gudongquanyiheji',


    '负债和所有者权益合计' : 'fuzhaihesuoyouzhequanyiheji',

}
